### PR TITLE
feat: Deploy To GitHub Releases and VSCode Extension Marketplace

### LINKED ISSUE #8: Add semantic-release to automatically release new versions to GitHub Releases and the VSCode extension store

### PR DESCRIPTION
**Pull request by zhenglin-charlie-li**
fix: https://github.com/casbin/casbin-vscode-plugin/issues/8

@hsluoyz Please note we need the following secret to publish to vscode extension marketplace, refer to https://github.com/HaaLeo/publish-vscode-extension
image

### CODE REVIEW

**Comment by nomeguy** [comment]
where to get VS_MARKETPLACE_TOKEN ?

**Comment by zhenglin-charlie-li** [comment]
> where to get VS_MARKETPLACE_TOKEN ?

can refer: 
https://github.com/marketplace/actions/publish-vs-code-extension
https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token

**Comment by nomeguy** [comment]
done 
image

**Comment by nomeguy** [comment]
@ZhengLin-Li CI failed

image

**Pull request merged**
