### PR TITLE
feat: add hover  for conf file

### PR DESCRIPTION
**Pull request by zhenglin-charlie-li**
feature is as what is shown below.

image

### CODE REVIEW

**Comment by zhenglin-charlie-li** [comment]
But I got a question: do we need to add `.vscode/launch.json` to the git? It is used to control the behavior when debugging our extension. I think adding `.vscode/launch.json` to git will help other contributors get started smoothly.

**Comment by nomeguy** [comment]
> But I got a question: do we need to add `.vscode/launch.json` to the git? It is used to control the behavior when debugging our extension. I think adding `.vscode/launch.json` to git will help other contributors get started smoothly.

sounds ok

**Comment by nomeguy** [comment]
If https://github.com/casbin/casbin-vscode-plugin/issues/8 is done first, this PR can be auto-released

**Comment by zhenglin-charlie-li** [comment]
> If #8 is done first, this PR can be auto-released

sure, this will also serve as a test to check if auto-release can work correctly.

**Pull request closed without merging**
